language: java

jdk:
  - oraclejdk8
## openjdk8 currently does not provide openjfx, so every PR would have to get checked by looking at the oraclejdk-build
#  - openjdk8

branches:
  only:
  - master

notifications:
  email: false

script:
  - mvn install -B -Dgpg.skip=true

before_script:
  - pip install --user codecov

after_success:
  - codecov

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"